services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DVC\AsyncPagination\Controller\ContentElement\AsyncPaginationWrapperController:

  DVC\AsyncPagination\Controller\AjaxEndpointController:

  DVC\AsyncPagination\EventListener\AddFrontendScriptToContentElementListener:

  DVC\AsyncPagination\EventListener\AddWrapperToContentElementListener:
